---
title: "Plots"
output: html_document
---

```{r,message=FALSE, echo=FALSE}
library(ggplot2)
library(dplyr)
library(gtable)
library(grid)
```

```{r, echo=FALSE}
c45_1s.data <- read.csv("c45_1s.csv")
ggplot(c45_1s.data, aes(Latency)) + geom_histogram(binwidth = (0.03), fill="#9999CC",colour = "black", na.rm=TRUE) + scale_x_continuous(limits = c(0, 0.8)) + ylim(0, 70) + labs(x="Latency (s)", y="FoG Detections [#]", title = "C4.5, 1s window")
```

```{r, echo=FALSE}
rf_1s.data <- read.csv("rf_1s.csv")
ggplot(rf_1s.data, aes(Latency)) + geom_histogram(binwidth = (0.03), fill="#9999CC",colour = "black", na.rm=TRUE) + scale_x_continuous(limits = c(0, 0.8)) + ylim(0, 70) + labs(x="Latency (s)", y="FoG Detections [#]", title = "RF, 1s window")
```
  
```{r, echo=FALSE}
c45_4s.data <- read.csv("c45_4s.csv")
ggplot(c45_4s.data, aes(Latency)) + geom_histogram(binwidth = (0.125), fill="#9999CC",colour = "black", na.rm=TRUE) + scale_x_continuous(limits = c(0, 2.125)) + ylim(0, 70) + labs(x="Latency (s)", y="FoG Detections [#]", title = "C4.5, 4s window")
```
  
```{r, echo=FALSE}
rf_4s.data <- read.csv("rf_4s.csv")
ggplot(rf_4s.data, aes(Latency)) + geom_histogram(binwidth = (0.125), fill="#9999CC",colour = "black", na.rm=TRUE) + scale_x_continuous(limits = c(0, 2.125)) + ylim(0, 70) + labs(x="Latency (s)", y="FoG Detections [#]", title = "RF, 4s window")
```

```{r, echo=FALSE}
rf_4s.data <- read.csv("sen-spe_latency.csv")

# two plots
p1 <- ggplot(rf_4s.data, aes(Time,minSenSpe)) + geom_line(colour = "blue", size= 1.2) + labs(x="Window length [s]", y="min(Sensitivity, Speci!city) [%]") + scale_x_continuous(limits = c(0, 8), breaks=seq(0,8,1)) + ylim(95, 100) + theme_bw()
p2 <- ggplot(rf_4s.data, aes(Time,latency)) + geom_line(colour = "green", linetype="dashed", size= 1.2) + labs(x="Window length [s]", y="Mean latency [s]") + scale_x_continuous(limits = c(0, 8), breaks=seq(0,8,1)) + ylim(0, 5)+ theme_bw() %+replace% theme(panel.background = element_rect(fill = NA))
p2

# extract gtable
g1 <- ggplot_gtable(ggplot_build(p1))
g2 <- ggplot_gtable(ggplot_build(p2))

# overlap the panel of 2nd plot on that of 1st plot
pp <- c(subset(g1$layout, name == "panel", se = t:r))
g <- gtable_add_grob(g1, g2$grobs[[which(g2$layout$name == "panel")]], pp$t, 
    pp$l, pp$b, pp$l)

# axis tweaks
ia <- which(g2$layout$name == "axis-l")
ga <- g2$grobs[[ia]]
ax <- ga$children[[2]]
ax$widths <- rev(ax$widths)
ax$grobs <- rev(ax$grobs)
ax$grobs[[1]]$x <- ax$grobs[[1]]$x - unit(1, "npc") + unit(0.15, "cm")
g <- gtable_add_cols(g, g2$widths[g2$layout[ia, ]$l], length(g$widths)-1)
g <- gtable_add_grob(g, ax, pp$t, length(g$widths)-1, pp$b)

grid.draw(g)


```

```{r, echo=FALSE}
rf_4s.data <- read.csv("sen-spe_latency.csv")

# two plots
ggplot(rf_4s.data, aes(Time,minSenSpe)) + geom_line(colour = "blue", size= 1.2) + labs(x="Window length [s]", y="min(Sensitivity, Speci!city) [%]") + scale_x_continuous(limits = c(0, 8), breaks=seq(0,8,1)) + ylim(95, 100) + theme_bw()

ggplot(rf_4s.data, aes(Time,latency)) + geom_line(colour = "green", linetype="dashed", size= 1.2) + labs(x="Window length [s]", y="Mean latency [s]") + scale_x_continuous(limits = c(0, 8), breaks=seq(0,8,1)) + ylim(0, 5)+ theme_bw() %+replace% theme(panel.background = element_rect(fill = NA))
```

```{r, echo=FALSE}
testRaw <- read.csv("patient2test1.csv")
testRaw2 <- read.csv("patient2test2.csv")
test <- dplyr::filter(testRaw, anno > 0) 
test2 <- dplyr::filter(testRaw2, anno > 0) 
ggplot(test, aes(time, AV+AHL+AHF, colour=(anno==2))) + geom_path()+ scale_x_continuous(limits = c(895000, 970000))
ggplot(test, aes(time, ULHF + ULV + ULHL, colour=(anno==2))) + geom_path()+ scale_x_continuous(limits = c(895000, 970000))
ggplot(test, aes(time, THF + TV + THL, colour=(anno==2))) + geom_path()+ scale_x_continuous(limits = c(895000, 970000))
```
